export const PERMISSIONS = {
  VIEW_VEHICLES: "view_vehicles",
  CREATE_VEHICLE: "create_vehicle",
  UPDATE_VEHICLE: "update_vehicle",
  DELETE_VEHICLE: "delete_vehicle",
  VIEW_VEHICLE_COST: "view_vehicle_cost",
  VIEW_VEHICLE_PROFIT: "view_vehicle_profit",
  VIEW_CUSTOMERS: "view_customers",
  CREATE_CUSTOMER: "create_customer",
  UPDATE_CUSTOMER: "update_customer",
  VIEW_LEADS: "view_leads",
  VIEW_ALL_LEADS: "view_all_leads",
  CREATE_LEAD: "create_lead",
  UPDATE_LEAD: "update_lead",
  ASSIGN_LEAD: "assign_lead",
  CREATE_FOLLOW_UP: "create_follow_up",
  UPDATE_FOLLOW_UP: "update_follow_up",
  CREATE_QUOTATION: "create_quotation",
  APPROVE_DISCOUNT: "approve_discount",
  RESERVE_VEHICLE: "reserve_vehicle",
  CREATE_INVOICE: "create_invoice",
  RECORD_PAYMENT: "record_payment",
  MANAGE_EXPORTS: "manage_exports",
  UPLOAD_DOCUMENTS: "upload_documents",
  VERIFY_DOCUMENTS: "verify_documents",
  MANAGE_MARKETING: "manage_marketing",
  VIEW_REPORTS: "view_reports",
  VIEW_FINANCE: "view_finance",
  MANAGE_USERS: "manage_users",
  MANAGE_SUBSCRIPTIONS: "manage_subscriptions",
  MANAGE_COMPANY_SETTINGS: "manage_company_settings",
  VIEW_AUDIT_LOGS: "view_audit_logs",
  USE_AI_ASSISTANT: "use_ai_assistant",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
