import { PERMISSIONS, type PermissionKey } from "@/lib/permissions/permissions";

export const BUSINESS_ROLE_OPTIONS = [
  {
    key: "company_owner",
    label: "Company Owner",
    description: "Owns the workspace and can manage all modules, billing, and users.",
  },
  {
    key: "general_manager",
    label: "General Manager",
    description: "Runs the dealership group with broad operations and reporting access.",
  },
  {
    key: "sales_manager",
    label: "Sales Manager",
    description: "Manages CRM, leads, quotations, reservations, and sales performance.",
  },
  {
    key: "salesperson",
    label: "Salesperson",
    description: "Works leads, follow-ups, customer records, and customer-facing quotations.",
  },
  {
    key: "accountant",
    label: "Accountant",
    description: "Manages payments, payables, receivables, finance, and accounting controls.",
  },
  {
    key: "inventory_manager",
    label: "Inventory Manager",
    description: "Controls stock intake, vehicle updates, costs, and vehicle documents.",
  },
  {
    key: "export_manager",
    label: "Export Manager",
    description: "Runs import/export orders, customs, shipping, and export documents.",
  },
  {
    key: "marketing_manager",
    label: "Marketing Manager",
    description: "Publishes listings, campaigns, marketplace sync, and social drafts.",
  },
  {
    key: "document_controller",
    label: "Document Controller",
    description: "Uploads, verifies, signs, and audits dealership documents.",
  },
  {
    key: "service_manager",
    label: "Service Manager",
    description: "Manages workshop orders, service jobs, inspections, and warranty claims.",
  },
  {
    key: "parts_manager",
    label: "Parts Manager",
    description: "Manages parts inventory, purchase orders, receipts, transfers, and suppliers.",
  },
  {
    key: "auditor",
    label: "Auditor",
    description: "Reviews reports, audit logs, documents, finance, and accounting history.",
  },
  {
    key: "other",
    label: "Other",
    description: "User role will be assigned later by a company administrator.",
  },
] as const;

export type BusinessRoleKey = (typeof BUSINESS_ROLE_OPTIONS)[number]["key"];

const businessRoleKeys = new Set<string>(BUSINESS_ROLE_OPTIONS.map((role) => role.key));

export function isBusinessRoleKey(value: unknown): value is BusinessRoleKey {
  return typeof value === "string" && businessRoleKeys.has(value);
}

export function getBusinessRoleOption(value: unknown) {
  const key = isBusinessRoleKey(value) ? value : "other";
  return BUSINESS_ROLE_OPTIONS.find((role) => role.key === key) ?? BUSINESS_ROLE_OPTIONS[BUSINESS_ROLE_OPTIONS.length - 1];
}

export type CompanyRoleTemplate = {
  roleKey: Exclude<BusinessRoleKey, "company_owner" | "other">;
  name: string;
  description: string;
  permissionKeys: PermissionKey[];
};

export const DEFAULT_COMPANY_ROLE_TEMPLATES: CompanyRoleTemplate[] = [
  {
    roleKey: "general_manager",
    name: "General Manager",
    description: "Broad operational access across stock, sales, finance, export, reports, alerts, chat, and AI.",
    permissionKeys: [
      PERMISSIONS.VIEW_VEHICLES,
      PERMISSIONS.CREATE_VEHICLE,
      PERMISSIONS.UPDATE_VEHICLE,
      PERMISSIONS.VIEW_VEHICLE_COST,
      PERMISSIONS.VIEW_VEHICLE_PROFIT,
      PERMISSIONS.MANAGE_VEHICLE_INTELLIGENCE,
      PERMISSIONS.VIEW_SALES,
      PERMISSIONS.UPDATE_QUOTATION,
      PERMISSIONS.VIEW_PAYMENTS,
      PERMISSIONS.VIEW_CUSTOMERS,
      PERMISSIONS.CREATE_CUSTOMER,
      PERMISSIONS.UPDATE_CUSTOMER,
      PERMISSIONS.VIEW_LEADS,
      PERMISSIONS.VIEW_ALL_LEADS,
      PERMISSIONS.CREATE_LEAD,
      PERMISSIONS.UPDATE_LEAD,
      PERMISSIONS.ASSIGN_LEAD,
      PERMISSIONS.CREATE_FOLLOW_UP,
      PERMISSIONS.UPDATE_FOLLOW_UP,
      PERMISSIONS.CREATE_QUOTATION,
      PERMISSIONS.APPROVE_DISCOUNT,
      PERMISSIONS.RESERVE_VEHICLE,
      PERMISSIONS.CREATE_INVOICE,
      PERMISSIONS.VIEW_EXPORTS,
      PERMISSIONS.MANAGE_EXPORTS,
      PERMISSIONS.UPDATE_EXPORT_STATUS,
      PERMISSIONS.VIEW_DOCUMENTS,
      PERMISSIONS.UPLOAD_DOCUMENTS,
      PERMISSIONS.VERIFY_DOCUMENTS,
      PERMISSIONS.MANAGE_SIGNATURE_REQUESTS,
      PERMISSIONS.MANAGE_MARKETING,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.MANAGE_REPORTS,
      PERMISSIONS.VIEW_ALERTS,
      PERMISSIONS.MANAGE_ALERTS,
      PERMISSIONS.USE_CHAT,
      PERMISSIONS.VIEW_FINANCE,
      PERMISSIONS.MANAGE_FINANCE,
      PERMISSIONS.VIEW_ACCOUNTING,
      PERMISSIONS.MANAGE_SUPPLIERS,
      PERMISSIONS.VIEW_SERVICE,
      PERMISSIONS.MANAGE_SERVICE,
      PERMISSIONS.VIEW_PARTS,
      PERMISSIONS.MANAGE_PARTS,
      PERMISSIONS.USE_AI_ASSISTANT,
      PERMISSIONS.VIEW_AI_AUTOMATION,
    ],
  },
  {
    roleKey: "sales_manager",
    name: "Sales Manager",
    description: "Sales leadership access for CRM, quotations, reservations, invoices, reports, alerts, chat, and AI.",
    permissionKeys: [
      PERMISSIONS.VIEW_VEHICLES,
      PERMISSIONS.VIEW_VEHICLE_COST,
      PERMISSIONS.VIEW_VEHICLE_PROFIT,
      PERMISSIONS.VIEW_SALES,
      PERMISSIONS.UPDATE_QUOTATION,
      PERMISSIONS.VIEW_PAYMENTS,
      PERMISSIONS.VIEW_CUSTOMERS,
      PERMISSIONS.CREATE_CUSTOMER,
      PERMISSIONS.UPDATE_CUSTOMER,
      PERMISSIONS.VIEW_LEADS,
      PERMISSIONS.VIEW_ALL_LEADS,
      PERMISSIONS.CREATE_LEAD,
      PERMISSIONS.UPDATE_LEAD,
      PERMISSIONS.ASSIGN_LEAD,
      PERMISSIONS.CREATE_FOLLOW_UP,
      PERMISSIONS.UPDATE_FOLLOW_UP,
      PERMISSIONS.CREATE_QUOTATION,
      PERMISSIONS.APPROVE_DISCOUNT,
      PERMISSIONS.RESERVE_VEHICLE,
      PERMISSIONS.CREATE_INVOICE,
      PERMISSIONS.VIEW_DOCUMENTS,
      PERMISSIONS.UPLOAD_DOCUMENTS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.MANAGE_REPORTS,
      PERMISSIONS.VIEW_ALERTS,
      PERMISSIONS.MANAGE_ALERTS,
      PERMISSIONS.USE_CHAT,
      PERMISSIONS.MANAGE_COMMISSIONS,
      PERMISSIONS.USE_AI_ASSISTANT,
    ],
  },
  {
    roleKey: "salesperson",
    name: "Salesperson",
    description: "Daily selling access for assigned leads, customers, follow-ups, quotations, and reservations.",
    permissionKeys: [
      PERMISSIONS.VIEW_VEHICLES,
      PERMISSIONS.VIEW_SALES,
      PERMISSIONS.VIEW_CUSTOMERS,
      PERMISSIONS.CREATE_CUSTOMER,
      PERMISSIONS.UPDATE_CUSTOMER,
      PERMISSIONS.VIEW_LEADS,
      PERMISSIONS.CREATE_LEAD,
      PERMISSIONS.UPDATE_LEAD,
      PERMISSIONS.CREATE_FOLLOW_UP,
      PERMISSIONS.UPDATE_FOLLOW_UP,
      PERMISSIONS.CREATE_QUOTATION,
      PERMISSIONS.RESERVE_VEHICLE,
      PERMISSIONS.VIEW_DOCUMENTS,
      PERMISSIONS.UPLOAD_DOCUMENTS,
      PERMISSIONS.VIEW_ALERTS,
      PERMISSIONS.USE_CHAT,
      PERMISSIONS.USE_AI_ASSISTANT,
    ],
  },
  {
    roleKey: "accountant",
    name: "Accountant",
    description: "Payment, finance, supplier, accounting, export, and financial reporting control.",
    permissionKeys: [
      PERMISSIONS.VIEW_VEHICLES,
      PERMISSIONS.VIEW_VEHICLE_COST,
      PERMISSIONS.VIEW_VEHICLE_PROFIT,
      PERMISSIONS.VIEW_SALES,
      PERMISSIONS.VIEW_PAYMENTS,
      PERMISSIONS.RECORD_PAYMENT,
      PERMISSIONS.VIEW_CUSTOMERS,
      PERMISSIONS.VIEW_EXPORTS,
      PERMISSIONS.VIEW_DOCUMENTS,
      PERMISSIONS.UPLOAD_DOCUMENTS,
      PERMISSIONS.VERIFY_DOCUMENTS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.MANAGE_REPORTS,
      PERMISSIONS.VIEW_FINANCE,
      PERMISSIONS.MANAGE_FINANCE,
      PERMISSIONS.MANAGE_COMMISSIONS,
      PERMISSIONS.VIEW_ACCOUNTING,
      PERMISSIONS.MANAGE_ACCOUNTING,
      PERMISSIONS.EXPORT_ACCOUNTING,
      PERMISSIONS.MANAGE_SUPPLIERS,
      PERMISSIONS.VIEW_AUDIT_LOGS,
      PERMISSIONS.USE_CHAT,
    ],
  },
  {
    roleKey: "inventory_manager",
    name: "Inventory Manager",
    description: "Vehicle intake, stock movement, costing, photos, documents, valuation, and branch stock control.",
    permissionKeys: [
      PERMISSIONS.VIEW_VEHICLES,
      PERMISSIONS.CREATE_VEHICLE,
      PERMISSIONS.UPDATE_VEHICLE,
      PERMISSIONS.DELETE_VEHICLE,
      PERMISSIONS.VIEW_VEHICLE_COST,
      PERMISSIONS.VIEW_VEHICLE_PROFIT,
      PERMISSIONS.MANAGE_VEHICLE_INTELLIGENCE,
      PERMISSIONS.VIEW_EXPORTS,
      PERMISSIONS.VIEW_DOCUMENTS,
      PERMISSIONS.UPLOAD_DOCUMENTS,
      PERMISSIONS.VERIFY_DOCUMENTS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.USE_CHAT,
      PERMISSIONS.USE_AI_ASSISTANT,
    ],
  },
  {
    roleKey: "export_manager",
    name: "Export Manager",
    description: "Import/export, logistics partners, customs, shipment costs, export documents, and export reports.",
    permissionKeys: [
      PERMISSIONS.VIEW_VEHICLES,
      PERMISSIONS.VIEW_CUSTOMERS,
      PERMISSIONS.VIEW_EXPORTS,
      PERMISSIONS.MANAGE_EXPORTS,
      PERMISSIONS.UPDATE_EXPORT_STATUS,
      PERMISSIONS.MANAGE_LOGISTICS_PARTNERS,
      PERMISSIONS.VIEW_DOCUMENTS,
      PERMISSIONS.UPLOAD_DOCUMENTS,
      PERMISSIONS.VERIFY_DOCUMENTS,
      PERMISSIONS.MANAGE_SIGNATURE_REQUESTS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.MANAGE_REPORTS,
      PERMISSIONS.VIEW_ALERTS,
      PERMISSIONS.MANAGE_ALERTS,
      PERMISSIONS.USE_CHAT,
      PERMISSIONS.USE_AI_ASSISTANT,
    ],
  },
  {
    roleKey: "marketing_manager",
    name: "Marketing Manager",
    description: "Listings, social content, campaigns, marketplace sync, lead sources, and marketing AI drafts.",
    permissionKeys: [
      PERMISSIONS.VIEW_VEHICLES,
      PERMISSIONS.VIEW_CUSTOMERS,
      PERMISSIONS.VIEW_LEADS,
      PERMISSIONS.CREATE_LEAD,
      PERMISSIONS.MANAGE_MARKETING,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.MANAGE_REPORTS,
      PERMISSIONS.USE_CHAT,
      PERMISSIONS.USE_AI_ASSISTANT,
    ],
  },
  {
    roleKey: "document_controller",
    name: "Document Controller",
    description: "Document intake, verification, checklist completion, signature requests, and signed archive.",
    permissionKeys: [
      PERMISSIONS.VIEW_VEHICLES,
      PERMISSIONS.VIEW_EXPORTS,
      PERMISSIONS.VIEW_CUSTOMERS,
      PERMISSIONS.VIEW_DOCUMENTS,
      PERMISSIONS.UPLOAD_DOCUMENTS,
      PERMISSIONS.VERIFY_DOCUMENTS,
      PERMISSIONS.MANAGE_SIGNATURE_REQUESTS,
      PERMISSIONS.VIEW_ALERTS,
      PERMISSIONS.MANAGE_ALERTS,
      PERMISSIONS.USE_CHAT,
      PERMISSIONS.USE_AI_ASSISTANT,
    ],
  },
  {
    roleKey: "service_manager",
    name: "Service Manager",
    description: "Workshop orders, job cards, technician assignment, inspection results, warranty claims, and service parts.",
    permissionKeys: [
      PERMISSIONS.VIEW_VEHICLES,
      PERMISSIONS.VIEW_CUSTOMERS,
      PERMISSIONS.VIEW_DOCUMENTS,
      PERMISSIONS.UPLOAD_DOCUMENTS,
      PERMISSIONS.VIEW_SERVICE,
      PERMISSIONS.MANAGE_SERVICE,
      PERMISSIONS.ASSIGN_SERVICE_JOBS,
      PERMISSIONS.MANAGE_WARRANTY_CLAIMS,
      PERMISSIONS.VIEW_PARTS,
      PERMISSIONS.MANAGE_PARTS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.VIEW_ALERTS,
      PERMISSIONS.MANAGE_ALERTS,
      PERMISSIONS.USE_CHAT,
    ],
  },
  {
    roleKey: "parts_manager",
    name: "Parts Manager",
    description: "Parts catalog, stock, purchase orders, receipts, transfers, reorder alerts, and supplier coordination.",
    permissionKeys: [
      PERMISSIONS.VIEW_SERVICE,
      PERMISSIONS.VIEW_PARTS,
      PERMISSIONS.MANAGE_PARTS,
      PERMISSIONS.MANAGE_PART_ORDERS,
      PERMISSIONS.TRANSFER_PARTS,
      PERMISSIONS.MANAGE_SUPPLIERS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.VIEW_ALERTS,
      PERMISSIONS.MANAGE_ALERTS,
      PERMISSIONS.USE_CHAT,
    ],
  },
  {
    roleKey: "auditor",
    name: "Auditor",
    description: "Read-focused access for audit logs, finance, accounting, documents, reports, and operational review.",
    permissionKeys: [
      PERMISSIONS.VIEW_VEHICLES,
      PERMISSIONS.VIEW_VEHICLE_COST,
      PERMISSIONS.VIEW_VEHICLE_PROFIT,
      PERMISSIONS.VIEW_SALES,
      PERMISSIONS.VIEW_PAYMENTS,
      PERMISSIONS.VIEW_CUSTOMERS,
      PERMISSIONS.VIEW_LEADS,
      PERMISSIONS.VIEW_EXPORTS,
      PERMISSIONS.VIEW_DOCUMENTS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.VIEW_FINANCE,
      PERMISSIONS.VIEW_ACCOUNTING,
      PERMISSIONS.VIEW_SERVICE,
      PERMISSIONS.VIEW_PARTS,
      PERMISSIONS.VIEW_BILLING,
      PERMISSIONS.VIEW_AUDIT_LOGS,
      PERMISSIONS.USE_CHAT,
    ],
  },
];
